# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vuln_scan_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtGui import QIcon
from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView, QTableWidgetItem, QAbstractItemView, QTableView, QFrame,QAction


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(Qt.WindowMinimizeButtonHint) # 显示最小化按钮
        MainWindow.setWindowFlags(Qt.WindowCloseButtonHint) # 显示关闭按钮
        MainWindow.setWindowFlags(Qt.MSWindowsFixedSizeDialogHint) # 固定大小， 无法进行最大化
        MainWindow.setWindowIcon(QIcon("main.jpg"))
        # MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(158, 99, 79, 255), stop:1 rgba(255, 255, 255, 255));")
        MainWindow.resize(1212, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab)
        self.treeWidget.setGeometry(QtCore.QRect(10, 70, 191, 591))
        self.treeWidget.setStyleSheet("border:2px groove gray;border-radius:10px;padding:0px 2px")
        # self.treeWidget.setObjectName("treeWidget")
        # self.treeWidget.headerItem().setText(0, "afsgdsfgsf")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setItalic(False)
        # font.setUnderline(False)
        # font.setWeight(50)
        # font.setStrikeOut(False)
        # font.setKerning(True)
        # self.treeWidget.headerItem().setFont(0, font)
        # brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # self.treeWidget.headerItem().setForeground(0, brush)
        # item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        # font = QtGui.QFont()
        # font.setStrikeOut(False)
        # item_0.setFont(0, font)
        # item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        # item_1 = QtWidgets.QTreeWidgetItem(item_0)
        # item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        # item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(209, 490, 481, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 20, 461, 141))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_2.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(700, 490, 151, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_2.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setGeometry(QtCore.QRect(0, 40, 75, 111))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_13 = QtWidgets.QLabel(self.splitter)
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setObjectName("label_4")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_2.setGeometry(QtCore.QRect(80, 40, 71, 111))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.comboBox_6 = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_3.setEnabled(True)
        self.comboBox_3.setMaxVisibleItems(9)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(859, 489, 311, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_3.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 20, 291, 141))
        self.textEdit_2.setObjectName("textEdit_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 1161, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        # self.pushButton.setStyleSheet('')
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText('http://127.0.0.1:8080/doUpload.action')
        self.lineEdit.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.gridLayout.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        self.gridLayout.addWidget(self.pushButton_2, 0, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}") # 设置背景色，当鼠标移动到 QPushButton 按钮时会变成一种颜色。
        self.gridLayout.addWidget(self.pushButton_3, 0, 5, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.resizeColumnsToContents() # 设置列宽高按照内容自适应
        self.tableWidget.resizeRowsToContents()
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget.horizontalHeader().setStyleSheet(
            "QHeaderView::section{background-color:rgb(155, 194, 230);color: black;};")
        # self.tableWidget.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeToContents)
        self.tableWidget.setGeometry(QtCore.QRect(210, 70, 960, 411))
        self.tableWidget.setStyleSheet("selection-background-color:lightblue;")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("漏洞地址")
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(255, 255, 127))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True) # 显示 水平表头
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        # self.tableWidget.horizontalHeader().setDefaultSectionSize(0)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True) # 去掉 垂直表头
        self.tableWidget.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeToContents)
        self.tableWidget.setColumnWidth(0 ,20)
        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows) # 选中一行
        self.tableWidget.setEditTriggers(QTableView.NoEditTriggers)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(640, 10, 540, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_12.setStyleSheet("color:Red")
        self.label_12.setAlignment(Qt.AlignRight)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(19, 9, 711, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        # self.groupBox_4.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 31, 671, 89))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setPlaceholderText('http://127.0.0.1:8080/doUpload.action')
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setPlaceholderText('输入 cookie -- 可选项')
        self.lineEdit_3.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px") # 设置圆角
        # self.lineEdit_3.setFrameShape(QtWidgets.QFrame.Box)
        # self.lineEdit_3.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.lineEdit_3.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);background-color: rgb(100, 149, 237);')
        self.gridLayout_2.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px")
        # self.comboBox_4.addItem("")
        # self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        # self.comboBox_5.addItem("")
        # self.comboBox_5.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_5, 1, 3, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(740, 10, 431, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setObjectName("groupBox_5")
        # self.groupBox_5.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 148, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_7.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_7.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 411, 141))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 160, 710, 69))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        # self.groupBox_6.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(12, 29, 500, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setPlaceholderText('127.0.0.1')
        self.lineEdit_4.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.gridLayout_4.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 2, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(510, 26, 180, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setPlaceholderText('5555')
        self.lineEdit_5.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.gridLayout_5.addWidget(self.lineEdit_5, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        self.gridLayout_5.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 250, 711, 411))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_7.setGeometry(QtCore.QRect(10, 10, 681, 371))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_7.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 60, 681, 311))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_5.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 681, 30))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.setText('whoami')
        self.lineEdit_6.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.gridLayout_6.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        self.gridLayout_6.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(740, 230, 431, 431))
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_7.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser_6.setGeometry(QtCore.QRect(10, 20, 411, 401))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_6.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 10, 646, 31))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_8.addWidget(self.radioButton_3, 0, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_8.addWidget(self.radioButton_4, 0, 1, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_8.addWidget(self.radioButton_5, 0, 2, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_8.addWidget(self.radioButton_6, 0, 3, 1, 1)
        self.layoutWidget7 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget7.setGeometry(QtCore.QRect(680, 350, 491, 30))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        self.gridLayout_9.addWidget(self.pushButton_10, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        self.gridLayout_9.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        self.gridLayout_9.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}\QPushButton{background-color:rgb(0,191,255)}")
        self.gridLayout_9.addWidget(self.pushButton_8, 0, 3, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_8.setGeometry(QtCore.QRect(19, 49, 1151, 281))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_8.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 20, 1131, 251))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setObjectName("textEdit_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_9.setGeometry(QtCore.QRect(19, 389, 1151, 271))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_9.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 2px")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 20, 1131, 241))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 350, 281, 31))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.setStyleSheet("QPushButton:hover{background-color:rgb(0,255,255)}")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(740, 30, 431, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_14.setStyleSheet("color:blue")
        self.label_14.setAlignment(Qt.AlignRight)
        # self.label_14.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);background-color: rgb(100, 149, 237);')
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1212, 0))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menu)
        self.menu_3.setObjectName("menu_3")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.actionFOFA = QtWidgets.QAction(MainWindow)
        self.actionFOFA.setObjectName("actionFOFA")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_9")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_9")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_9")
        self.menu_3.addAction(self.action_8)
        self.menu_3.addAction(self.action_9)
        self.menu_3.addAction(self.action_10)
        self.menu_3.addAction(self.action_11)
        self.menu_3.addAction(self.action_12)
        self.action=QAction("action",self)
        self.action.setShortcut("Ctrl+d")
        self.menu.addAction(self.action)
        self.menu.addAction(self.actionFOFA)
        self.menu.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.action_6)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())



        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
      

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GodScan by Guoke324"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        # self.treeWidget.setSortingEnabled(False)
        # self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "1"))
        # self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "1212"))
        # self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "1212"))
        # self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "1221"))
        # self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "可利用脚本"))
        self.groupBox.setTitle(_translate("MainWindow", "Scanner log"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Setting"))
        self.label_13.setText(_translate("MainWindow", "回显方式："))
        self.label_2.setText(_translate("MainWindow", "超时设置:"))
        self.label_3.setText(_translate("MainWindow", "线程设置："))
        self.label_4.setText(_translate("MainWindow", "头部设置："))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "全部"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "存在"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "不存在"))
        self.comboBox.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox.setItemText(1, _translate("MainWindow", "10"))
        self.comboBox.setItemText(2, _translate("MainWindow", "15"))
        self.comboBox.setItemText(3, _translate("MainWindow", "30"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "10"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "15"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "随机"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "自定义"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Headers"))
        self.pushButton.setText(_translate("MainWindow", "清除日志"))
        self.pushButton_4.setText(_translate("MainWindow", "加载脚本"))
        self.label.setText(_translate("MainWindow", "目标地址："))
        self.pushButton_2.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_3.setText(_translate("MainWindow", "一键利用"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "漏洞名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "     危险等级    "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Poc 路径"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "检测结果"))
        self.label_12.setText(_translate("MainWindow", "免责声明:本工具仅供安全测试学习用途,禁止非法使用，否则造成的严重后果与本项目无关！"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "漏洞扫描"))
        self.groupBox_4.setTitle(_translate("MainWindow", "漏洞信息"))
        self.label_6.setText(_translate("MainWindow", "Cookies："))
        self.label_5.setText(_translate("MainWindow", "目标地址："))
        self.label_7.setText(_translate("MainWindow", "漏洞类型："))
        # self.comboBox_4.setItemText(0, _translate("MainWindow", "testr"))
        # self.comboBox_4.setItemText(1, _translate("MainWindow", "test"))
        self.label_8.setText(_translate("MainWindow", "漏洞名称："))
        # self.comboBox_5.setItemText(0, _translate("MainWindow", "test"))
        # self.comboBox_5.setItemText(1, _translate("MainWindow", "123123"))
        self.groupBox_5.setTitle(_translate("MainWindow", "headers"))
        self.radioButton.setText(_translate("MainWindow", "随机"))
        self.radioButton_2.setText(_translate("MainWindow", "自定义"))
        self.groupBox_6.setTitle(_translate("MainWindow", "反弹shell"))
        self.label_9.setText(_translate("MainWindow", "反弹地址："))
        self.label_10.setText(_translate("MainWindow", "反弹端口："))
        self.pushButton_5.setText(_translate("MainWindow", "反弹shell"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "基本信息"))
        self.label_11.setText(_translate("MainWindow", "输入命令"))
        self.pushButton_6.setText(_translate("MainWindow", "执行命令"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "命令执行"))
        self.groupBox_7.setTitle(_translate("MainWindow", "logs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "漏洞利用"))
        self.radioButton_3.setText(_translate("MainWindow", "Url 编码/解码"))
        self.radioButton_4.setText(_translate("MainWindow", "Base64 编码/解码"))
        self.radioButton_5.setText(_translate("MainWindow", "Hex 编码/解码"))
        self.radioButton_6.setText(_translate("MainWindow", "Unicode 编码/解码"))
        self.pushButton_10.setText(_translate("MainWindow", "清空输入"))
        self.pushButton_9.setText(_translate("MainWindow", "清空输出"))
        self.pushButton_7.setText(_translate("MainWindow", "开始编码"))
        self.pushButton_8.setText(_translate("MainWindow", "开始解码"))
        self.groupBox_8.setTitle(_translate("MainWindow", "InPut"))
        self.groupBox_9.setTitle(_translate("MainWindow", "OutPut"))
        self.pushButton_11.setText(_translate("MainWindow", "来和我玩吧"))
        self.label_14.setText(_translate("MainWindow", "为我使用方便，现只支持中文与对应编码之间的转换，其他另请高明！"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "编码解码"))
        self.menu.setTitle(_translate("MainWindow", "系统菜单"))
        self.menu_3.setTitle(_translate("MainWindow", "主题设置"))
        self.menu_2.setTitle(_translate("MainWindow", "使用帮助"))
        self.action.setText(_translate("MainWindow", "模块详情"))
        self.actionFOFA.setText(_translate("MainWindow", "FOFA插件"))
        self.action_2.setText(_translate("MainWindow", "关于作者"))
        self.action_3.setText(_translate("MainWindow", "帮助"))
        self.action_4.setText(_translate("MainWindow", "更新"))
        self.action_5.setText(_translate("MainWindow", "关于作者"))
        self.action_6.setText(_translate("MainWindow", "项目地址"))
        self.action_8.setText(_translate("MainWindow", "默认风格"))
        self.action_9.setText(_translate("MainWindow", "灰暗炫酷"))
        self.action_10.setText(_translate("MainWindow", "蓝色渐变"))
        self.action_11.setText(_translate("MainWindow", "青青草原"))
        self.action_12.setText(_translate("MainWindow", "test"))
